import turtle

a=int(input('Выберите ленту: 1-прямая 2-галочка 3-простой бантик '))
t=turtle.Turtle()
t.hideturtle()
t.color('red')
t.penup()
t.goto(-200, 330)
t.pendown()
t.write('С днем победы!', font=('Times New Roman', 50, 'normal'))
if a==1:
    b=turtle.Turtle()
    b.color('black')
    b.shape('square')
    b.pensize(21)
    b.hideturtle()
    b.penup()
    b.goto(-200, -20)
    b.pendown()
    b.stamp()
    b.goto(200, -20)
    b.stamp()
    
    o=turtle.Turtle()
    o.color('orange')
    o.shape('square')
    o.hideturtle()
    o.pensize(21)
    o.penup()
    o.goto(-200, 0)
    o.pendown()
    o.stamp()
    o.goto(200, 0)
    o.stamp()
    
    b.penup()
    b.goto(-200, 20)
    b.pendown()
    b.stamp()
    b.goto(200, 20)
    b.stamp()
    
    o.penup()
    o.goto(-200, 40)
    o.pendown()
    o.stamp()
    o.goto(200, 40)
    o.stamp()
    
    b.penup()
    b.goto(-200, 60)
    b.pendown()
    b.stamp()
    b.goto(200, 60)
    b.stamp()
elif a==2:
    b=turtle.Turtle()
    b.color('black')
    b.shape('square')
    b.pensize(21)
    b.hideturtle()
    b.penup()
    b.goto(-100, -100)
    b.pendown()
    b.stamp()
    b.goto(0, 300)
    b.stamp()

    o=turtle.Turtle()
    o.color('orange')
    o.shape('square')
    o.hideturtle()
    o.pensize(21)
    o.hideturtle()
    o.penup()
    o.goto(-80, -100)
    o.pendown()
    o.stamp()
    o.goto(20, 300)
    o.stamp()

    b.penup()
    b.goto(-60, -100)
    b.pendown()
    b.stamp()
    b.goto(40, 300)
    b.stamp()
    
    o.penup()
    o.goto(-40, -100)
    o.pendown()
    o.stamp()
    o.goto(60, 300)
    o.stamp()
    
    b.penup()
    b.goto(-20, -100)
    b.pendown()
    b.stamp()
    b.goto(80, 300)
    b.stamp()

    b.penup()
    b.goto(0, 300)
    b.pendown()
    b.stamp()
    b.goto(100, -100)
    b.stamp()

    o.penup()
    o.goto(20, 300)
    o.pendown()
    o.stamp()
    o.goto(120, -100)
    o.stamp()

    b.penup()
    b.goto(40, 300)
    b.pendown()
    b.stamp()
    b.goto(140, -100)
    b.stamp()

    o.penup()
    o.goto(60, 300)
    o.pendown()
    o.stamp()
    o.goto(160, -100)
    o.stamp()

    b.penup()
    b.goto(80, 300)
    b.pendown()
    b.stamp()
    b.goto(180, -100)
    b.stamp()

elif a==3:
    b=turtle.Turtle()
    b.color('black')
    b.shape('square')
    b.pensize(21)
    b.hideturtle()
    b.penup()
    b.goto(-140, 0)
    b.pendown()
    b.goto(140, 0)
    
    o=turtle.Turtle()
    o.color('orange')
    o.shape('square')
    o.hideturtle()
    o.pensize(21)
    o.penup()
    o.goto(-130, 20)
    o.pendown()
    o.goto(130, 20)
    
    b.penup()
    b.goto(-120, 40)
    b.pendown()
    b.goto(120, 40)
    
    o.penup()
    o.goto(-110, 60)
    o.pendown()
    o.goto(110, 60)
    
    b.penup()
    b.goto(-100, 80)
    b.pendown()
    b.goto(100, 80)

    b.penup()
    b.goto(-100, 80)
    b.pendown()
    b.goto(200, -80)
    b.stamp()

    o.penup()
    o.goto(-110, 60)
    o.pendown()
    o.goto(200, -100)
    o.stamp()

    b.penup()
    b.goto(-120, 40)
    b.pendown()
    b.goto(200, -120)
    b.stamp()
    
    o.penup()
    o.goto(-130, 20)
    o.pendown()
    o.goto(200, -140)
    o.stamp()
    
    b.penup()
    b.goto(-140, 0)
    b.pendown()
    b.goto(200, -160)
    b.stamp()

    b.penup()
    b.goto(100, 80)
    b.pendown()
    b.goto(-200, -80)
    b.stamp()

    o.penup()
    o.goto(110, 60)
    o.pendown()
    o.goto(-200, -100)
    o.stamp()

    b.penup()
    b.goto(120, 40)
    b.pendown()
    b.goto(-200, -120)
    b.stamp()
    
    o.penup()
    o.goto(130, 20)
    o.pendown()
    o.goto(-200, -140)
    o.stamp()
    
    b.penup()
    b.goto(140, 0)
    b.pendown()
    b.goto(-200, -160)
    b.stamp()
